name: Deploy Glue Scripts to S3

on:
  push:
    branches:
      - master   # run only on main branch pushes
  workflow_dispatch:  # allow manual trigger

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Python scripts to S3
        run: |
          BUCKET_NAME="batch89-pyspark"    # 🔹 change this
          S3_PATH="CustomerSCD1JOBS/"                 # 🔹 folder inside bucket
          
          echo "Uploading .py files to s3://$BUCKET_NAME/$S3_PATH"
          aws s3 cp ./ s3://$BUCKET_NAME/$S3_PATH --recursive --exclude "*" --include "*.py"
